# Generated by Django 4.2.3 on 2023-07-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('email', models.EmailField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('desciption', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
